apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  creationTimestamp: null
  labels:
    app: nginx
    role: webserver
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 25m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 200Mi
status: {}
